### ISSUE TITLE
Iron farm generates nothing 

### ISSUE THREAD

**Issue by Eren-1997** [awesomeshot5051/MobFarms#2]
When I place down an iron farm, it doesn't generate anything. I disabled every other mod I had installed, and it still doesn't do anything, so it can't be an incompatibility. I'm neoforge and 1.21.1 btw

**Comment by awesomeshot5051** [comment]
Im sorry about that. I forgot to remove a particular part of the code. I'll update it tonight when I'm able to get on my computer. Look for an update on Modrinth tonight at the earliest and/or CurseForge Tuesday at the latest.
There will also be an update to some of the other farms as there are some bugs I've caught. If you find any more bugs please let me know. 
If you have any suggestions, you can open an issue with the enhancement tag.

**Comment by Eren-1997** [comment]
Thanks! I'll keep an eye out :3

**Comment by Eren-1997** [comment]
Also just saw the blaze one doesn't do anything either, just in case you didn't know

**Comment by awesomeshot5051** [comment]
I'll update both. If you're willing to, you can be my bug tester. I have a lot on my plate so I'd don't necessarily have time to test every single thing in a mod. If you're interested, DM me on discord. U-name is the same as GitHub.

**Comment by Eren-1997** [comment]
Sent!
